version: '3'

services:
    redis_session:
        image: "redis:latest"
        ports:
            - "6379:6379"
        volumes:
            - "./data/redis:/data/redis"

    postgresql:
        image: "postgres:latest"
        ports:
            - "5432:5432"
        volumes:
            - "./postgres/init:/data/postgresql"
        environment:
            POSTGRES_USER: shumiya
            POSTGRES_PASSWORD: shumiya
            POSTGRES_DB: shumi_db
            POSTGRES_INITDB_ARGS: "--encoding=UTF-8"

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
        environment:
            - discovery.type=single-node
            - cluster.name=docker-cluster
            - bootstrap.memory_lock=true
        ports:
            - 9200:9200
        volumes:
            - ./es-data:/usr/share/elasticsearch/data